SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `daidakaram-test`.`ProductCar` 
CHANGE COLUMN `CarId` `Make` VARCHAR(45) NULL DEFAULT NULL ,
ADD COLUMN `Model` VARCHAR(45) NULL DEFAULT NULL AFTER `Make`,
ADD COLUMN `Variant` VARCHAR(45) NULL DEFAULT NULL AFTER `Model`,
ADD COLUMN `Body` VARCHAR(45) NULL DEFAULT NULL AFTER `Variant`,
ADD COLUMN `Type` VARCHAR(45) NULL DEFAULT NULL AFTER `Body`,
ADD COLUMN `YearFrom` INT(11) NULL DEFAULT NULL AFTER `Type`,
ADD COLUMN `YearTo` INT(11) NULL DEFAULT NULL AFTER `YearFrom`,
ADD COLUMN `EngineCcm` INT(11) NULL DEFAULT NULL AFTER `YearTo`,
ADD COLUMN `EngineHp` INT(11) NULL DEFAULT NULL AFTER `EngineCcm`,
ADD COLUMN `EngineKw` INT(11) NULL DEFAULT NULL AFTER `EngineHp`,
ADD COLUMN `EngineFuel` VARCHAR(45) NULL DEFAULT NULL AFTER `EngineKw`;

CREATE TABLE IF NOT EXISTS `daidakaram-test`.`CompatibilitySetting` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Make` VARCHAR(45) NULL DEFAULT NULL,
  `Model` VARCHAR(45) NULL DEFAULT NULL,
  `Variant` VARCHAR(45) NULL DEFAULT NULL,
  `ProductId` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
