SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `daidakaram`.`ProductCar` 
DROP COLUMN `Make`,
ADD COLUMN `Make` VARCHAR(45) NULL DEFAULT NULL AFTER `ProductId`;

CREATE TABLE IF NOT EXISTS `daidakaram`.`CompatibilitySetting` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Make` VARCHAR(45) NULL DEFAULT NULL,
  `Model` VARCHAR(45) NULL DEFAULT NULL,
  `Variant` VARCHAR(45) NULL DEFAULT NULL,
  `ProductId` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
