SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `daidakaram`.`Car` 
ADD COLUMN `EngineCcm` INT(11) NULL DEFAULT NULL AFTER `YearTo`,
ADD COLUMN `EngineHp` INT(11) NULL DEFAULT NULL AFTER `EngineCcm`,
ADD COLUMN `EngineKw` INT(11) NULL DEFAULT NULL AFTER `EngineHp`,
ADD COLUMN `EngineFuel` VARCHAR(45) NULL DEFAULT NULL AFTER `EngineKw`,
ADD COLUMN `KType` INT(11) NULL DEFAULT NULL AFTER `EngineFuel`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
