
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Entry entry1;

	private global::Gtk.Button btnBrowse;

	private global::Gtk.Button btnStart;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label1;

	private global::Gtk.Label lblCount;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button btnRefresh;

	private global::Gtk.Button btn;

	private global::Gtk.HBox hbox3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView tvLog;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(15));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.hbox2.Add (this.entry1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry1]));
		w1.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnBrowse = new global::Gtk.Button ();
		this.btnBrowse.CanFocus = true;
		this.btnBrowse.Name = "btnBrowse";
		this.btnBrowse.UseUnderline = true;
		this.btnBrowse.Label = global::Mono.Unix.Catalog.GetString ("Browse");
		this.hbox2.Add (this.btnBrowse);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnBrowse]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnStart = new global::Gtk.Button ();
		this.btnStart.CanFocus = true;
		this.btnStart.Name = "btnStart";
		this.btnStart.UseUnderline = true;
		this.btnStart.Label = global::Mono.Unix.Catalog.GetString ("Import");
		this.hbox2.Add (this.btnStart);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnStart]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Available products:");
		this.hbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.lblCount = new global::Gtk.Label ();
		this.lblCount.Name = "lblCount";
		this.lblCount.LabelProp = global::Mono.Unix.Catalog.GetString ("<Unknown>");
		this.hbox1.Add (this.lblCount);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblCount]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnRefresh = new global::Gtk.Button ();
		this.btnRefresh.CanFocus = true;
		this.btnRefresh.Name = "btnRefresh";
		this.btnRefresh.UseUnderline = true;
		this.btnRefresh.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		this.hbox4.Add (this.btnRefresh);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnRefresh]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btn = new global::Gtk.Button ();
		this.btn.CanFocus = true;
		this.btn.Name = "btn";
		this.btn.UseUnderline = true;
		this.btn.Label = global::Mono.Unix.Catalog.GetString ("Import");
		this.hbox4.Add (this.btn);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btn]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox4]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvLog = new global::Gtk.TextView ();
		this.tvLog.CanFocus = true;
		this.tvLog.Name = "tvLog";
		this.tvLog.Editable = false;
		this.GtkScrolledWindow.Add (this.tvLog);
		this.hbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkScrolledWindow]));
		w12.Position = 0;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w13.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 418;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnBrowse.Clicked += new global::System.EventHandler (this.OnBtnBrowseClicked);
		this.btnStart.Clicked += new global::System.EventHandler (this.OnBtnImportClicked);
		this.btnRefresh.Clicked += new global::System.EventHandler (this.OnBtnRefreshClicked);
		this.btn.Clicked += new global::System.EventHandler (this.OnBtnImportProductsClick);
		this.tvLog.InsertAtCursor += new global::Gtk.InsertAtCursorHandler (this.onTvLogInsertAtCrusor);
	}
}
